Repository boddolk/LibraryManager, pull requests merged in 2024-11, with the labels that each got.

#11 Edit User Form Added
  libraryMeneger/EditUserInfo.Designer.cs
  libraryMeneger/EditUserInfo.cs
  libraryMeneger/EditUserInfo.resx
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#12 8 create db classes and interfaces
  libraryMeneger/DataAccess.cs
  libraryMeneger/libraryMeneger.csproj
  libraryMeneger/packages.config
Labels: enhancement

#14 Hierarchy added
  libraryMeneger/AdminUser.cs
  libraryMeneger/BaseUser.cs
  libraryMeneger/RegularUser.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#15 Add classes for books
  libraryMeneger/BookStatManager.cs
  libraryMeneger/GenBook.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#16 Stable connection to db established
  UsersAndBooks.db
  libraryMeneger/App.config
  libraryMeneger/DataAccess.cs
  libraryMeneger/LogInForm.cs
  libraryMeneger/Program.cs
  libraryMeneger/libraryMeneger.csproj
  libraryMeneger/packages.config
Labels: enhancement

#20 17 add main logic to the login form conection
  libraryMeneger/LogInForm.cs
  libraryMeneger/UserRepository.cs
Labels: bug

#26 final logic was addes
  libraryMeneger/EditUserInfo.cs
  libraryMeneger/SingUp.cs
  libraryMeneger/UserRepository.cs
Labels: bug, duplicate

#27 BooksRepository and its interface were added.
  libraryMeneger/BooksRepository.cs
  libraryMeneger/GenBook.cs
  libraryMeneger/IBooksRepository.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#31 Aded general combo box
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
  libraryMeneger/GenBook.cs
Labels: enhancement

#33 Some changes in admin form
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
Labels: bug

#35 Added methods for getting status.
  UsersAndBooks.db
  libraryMeneger/App.config
  libraryMeneger/BooksRepository.cs
  libraryMeneger/DataAccess.cs
  libraryMeneger/EditUserInfo.cs
  libraryMeneger/IStatusRepository.cs
  libraryMeneger/IUserRepository.cs
  libraryMeneger/LogInForm.cs
  libraryMeneger/SingUp.cs
  libraryMeneger/StatusRepository.cs
  libraryMeneger/UserRepository.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#36 Added a deletion frame
  libraryMeneger/AdminForm.cs
Labels: enhancement

#37 Completed delete function
  libraryMeneger/AdminForm.cs
  libraryMeneger/BookAddForm.cs
  libraryMeneger/GenBook.cs
Labels: bug

#41 Add form fix and complite
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
  libraryMeneger/BookAddForm.Designer.cs
  libraryMeneger/BookAddForm.cs
  libraryMeneger/BookEditForm.Designer.cs
  libraryMeneger/BookEditForm.cs
  libraryMeneger/EditUserInfo.cs
Labels: enhancement

#45 Aded form for status changes
  libraryMeneger/ReturnBookForm.Designer.cs
  libraryMeneger/ReturnBookForm.cs
  libraryMeneger/ReturnBookForm.resx
  libraryMeneger/ToIssueForm.Designer.cs
  libraryMeneger/ToIssueForm.cs
  libraryMeneger/ToIssueForm.resx
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#46 Add book reserve form
  libraryMeneger/ReservePlus.Designer.cs
  libraryMeneger/ReservePlus.cs
  libraryMeneger/ReservePlus.resx
  libraryMeneger/UserForm.Designer.cs
  libraryMeneger/UserForm.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#54 Intermediate result of the issue form
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
  libraryMeneger/ToIssueForm.Designer.cs
  libraryMeneger/ToIssueForm.cs
Labels: enhancement

#55 Getting books and its status
  libraryMeneger/BookStatManager.cs
  libraryMeneger/StatusRepository.cs
Labels: enhancement

#58 Add issue function
  libraryMeneger/BookStatManager.cs
  libraryMeneger/LogInForm.cs
  libraryMeneger/ToIssueForm.cs
Labels: enhancement

#59 Get history method was added.
  libraryMeneger/BorrowHistoryRepository.cs
  libraryMeneger/IBorrowHistoryRepository.cs
  libraryMeneger/StatusRepository.cs
Labels: bug, enhancement

#60 Fixed
  libraryMeneger/BorrowHistoryRepository.cs
  libraryMeneger/IStatusRepository.cs
  libraryMeneger/StatusRepository.cs
Labels: bug, enhancement

#61 Aded the frame of the return form functions
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
  libraryMeneger/ReturnBookForm.Designer.cs
  libraryMeneger/ReturnBookForm.cs
Labels: enhancement

#64 Base logic
  libraryMeneger/HistoryForm.Designer.cs
  libraryMeneger/HistoryForm.cs
  libraryMeneger/HistoryForm.resx
  libraryMeneger/UserForm.Designer.cs
  libraryMeneger/UserForm.cs
  libraryMeneger/libraryMeneger.csproj
Labels: enhancement

#66 Update for some repository methods
  libraryMeneger/HistoryForm.Designer.cs
  libraryMeneger/HistoryForm.cs
  libraryMeneger/HistoryForm.resx
  libraryMeneger/IStatusRepository.cs
  libraryMeneger/StatusRepository.cs
  libraryMeneger/UserForm.Designer.cs
  libraryMeneger/UserForm.cs
  libraryMeneger/libraryMeneger.csproj
Labels: duplicate

#67 62 add user history
  libraryMeneger/BookStatManager.cs
  libraryMeneger/BooksRepository.cs
  libraryMeneger/BorrowHistoryRepository.cs
  libraryMeneger/HistoryForm.Designer.cs
  libraryMeneger/HistoryForm.cs
  libraryMeneger/IBooksRepository.cs
  libraryMeneger/IBorrowHistoryRepository.cs
  libraryMeneger/LogInForm.cs
  libraryMeneger/UserForm.cs
Labels: enhancement

#68 Add full functional for issue admin form
  libraryMeneger/StatusRepository.cs
  libraryMeneger/ToIssueForm.Designer.cs
  libraryMeneger/ToIssueForm.cs
Labels: bug, enhancement

#69 Aded final return functional for admin and fixed some dags
  libraryMeneger/ReturnBookForm.Designer.cs
  libraryMeneger/ReturnBookForm.cs
  libraryMeneger/StatusRepository.cs
  libraryMeneger/ToIssueForm.cs
Labels: bug, enhancement

#72 Fixed user history bug
  libraryMeneger/BorrowHistoryRepository.cs
  libraryMeneger/HistoryForm.Designer.cs
  libraryMeneger/HistoryForm.cs
  libraryMeneger/UserForm.Designer.cs
  libraryMeneger/UserForm.cs
Labels: bug, enhancement

#73 Fixed transitions between windows
  UsersAndBooks.db
  libraryMeneger/AdminForm.Designer.cs
  libraryMeneger/AdminForm.cs
  libraryMeneger/BookAddForm.Designer.cs
  libraryMeneger/BookAddForm.cs
  libraryMeneger/BookEditForm.Designer.cs
  libraryMeneger/BookEditForm.cs
  libraryMeneger/EditUserInfo.Designer.cs
  libraryMeneger/EditUserInfo.cs
  libraryMeneger/HistoryForm.cs
  libraryMeneger/IStatusRepository.cs
  libraryMeneger/LogInForm.cs
  libraryMeneger/Program.cs
  libraryMeneger/ReservePlus.Designer.cs
  libraryMeneger/ReservePlus.cs
  libraryMeneger/ReturnBookForm.Designer.cs
  libraryMeneger/ReturnBookForm.cs
  libraryMeneger/SingUp.cs
  libraryMeneger/StatusRepository.cs
  libraryMeneger/ToIssueForm.Designer.cs
  libraryMeneger/ToIssueForm.cs
  libraryMeneger/UserForm.Designer.cs
  libraryMeneger/UserForm.cs
Labels: bug, enhancement, help wanted
